#ifndef CAL_STAT_DISPLAY_LIB_GLOBAL_H
#define CAL_STAT_DISPLAY_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAL_STAT_DISPLAY_LIB_LIBRARY)
#  define CAL_STAT_DISPLAY_LIB_EXPORT Q_DECL_EXPORT
#else
#  define CAL_STAT_DISPLAY_LIB_EXPORT Q_DECL_IMPORT
#endif

#endif // CAL_STAT_DISPLAY_LIB_GLOBAL_H
