#ifndef MEASDOCXML_GLOBAL_H
#define MEASDOCXML_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MEASDOCXML_LIBRARY)
#  define MEASDOCXML_EXPORT Q_DECL_EXPORT
#else
#  define MEASDOCXML_EXPORT Q_DECL_IMPORT
#endif

#endif // MEASDOCXML_GLOBAL_H
