#ifndef XY_REGRESSION_PLOT_GLOBAL_H
#define XY_REGRESSION_PLOT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XY_REGRESSION_PLOT_LIBRARY)
#  define XY_REGRESSION_PLOT_EXPORT Q_DECL_EXPORT
#else
#  define XY_REGRESSION_PLOT_EXPORT Q_DECL_IMPORT
#endif

#endif // XY_REGRESSION_PLOT_GLOBAL_H
