#ifndef QSTRING_UTILITIES_GLOBAL_H
#define QSTRING_UTILITIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSTRING_UTILITIES_LIBRARY)
#  define QSTRING_UTILITIES_EXPORT Q_DECL_EXPORT
#else
#  define QSTRING_UTILITIES_EXPORT Q_DECL_IMPORT
#endif

#endif // QSTRING_UTILITIES_GLOBAL_H
