#ifndef GEOCOORDINATES_GLOBAL_H
#define GEOCOORDINATES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GEOCOORDINATES_LIBRARY)
#  define GEOCOORDINATES_EXPORT Q_DECL_EXPORT
#else
#  define GEOCOORDINATES_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOCOORDINATES_GLOBAL_H
