#ifndef TINYXMLWRITER_GLOBAL_H
#define TINYXMLWRITER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TINYXMLWRITER_LIBRARY)
#  define TINYXMLWRITER_EXPORT Q_DECL_EXPORT
#else
#  define TINYXMLWRITER_EXPORT Q_DECL_IMPORT
#endif

#endif // TINYXMLWRITER_GLOBAL_H
