#ifndef MEASDOC_FROM_MC_DATA_GLOBAL_H
#define MEASDOC_FROM_MC_DATA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MEASDOC_FROM_MC_DATA_LIBRARY)
#  define MEASDOC_FROM_MC_DATA_EXPORT Q_DECL_EXPORT
#else
#  define MEASDOC_FROM_MC_DATA_EXPORT Q_DECL_IMPORT
#endif

#endif // MEASDOC_FROM_MC_DATA_GLOBAL_H
